// FAKE DATA
export const books = [
  {
    id: 1,
    title: "ERYS",
    url: "https://i.ibb.co/bFjSW72/jaden.png",
    originalPrice: 49.95,
    salePrice: 14.95,
    rating: 4.5,
  },
  {
    id: 2,
    title: "At Long Last A$AP",
    url: "https://i.ibb.co/fDpVLvD/rocky.jpg",
    originalPrice: 39,
    salePrice: null,
    rating: 5,
  },
  {
    id: 3,
    title: "Take Time",
    url: "https://i.ibb.co/7CgCD3F/giveon.png",
    originalPrice: 29,
    salePrice: null,
    rating: 5,
  },
  {
    id: 4,
    title: "Dark Sky Paradise",
    url: "https://i.ibb.co/hWqK9tR/bigsean.jpg",
    originalPrice: 44,
    salePrice: 19,
    rating: 4.5,
  },
  {
    id: 5,
    title: "After Hours",
    url: "https://i.ibb.co/f18nQcV/after.png",
    originalPrice: 32,
    salePrice: null,
    rating: 5,
  },
  {
    id: 6,
    title: "Purpose",
    url: "https://i.ibb.co/9TTGPhz/justin.png",
    originalPrice: 70,
    salePrice: 12.5,
    rating: 5,
  },
  {
    id: 7,
    title: "An Evening with Silk Sonic",
    url: "https://i.ibb.co/Jn4C4TJ/bruno.jpg",
    originalPrice: 11,
    salePrice: 10,
    rating: 4,
  },
  {
    id: 8,
    title: "Good Kid, m.A.A.d city",
    url: "https://i.ibb.co/dbyJfn1/kendrick.jpg",
    originalPrice: 38,
    salePrice: 17.95,
    rating: 4.5,
  },
  {
    id: 9,
    title: "Late Registration",
    url: "https://i.ibb.co/k4mGzcT/kanye.jpg",
    originalPrice: 35,
    salePrice: 19.95,
    rating: 4.5,
  },
  {
    id: 10,
    title: "Trilogy",
    url: "https://i.ibb.co/S3ZMChc/theweeknd.png",
    originalPrice: 40,
    salePrice: null,
    rating: 5,
  },
  {
    id: 11,
    title: "Yeezus",
    url: "https://i.ibb.co/1z5PhHM/yeezus.png",
    originalPrice: 30,
    salePrice: 20,
    rating: 5,
  },
  {
    id: 12,
    title: "Random Access Memories",
    url: "https://i.ibb.co/3SQSKWw/daft.jpg",
    originalPrice: 30,
    salePrice: 12.95,
    rating: 4.5,
  },
];